version: "2"
services: 
  mysql: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - ${PORT}:${PORT}
    links:
      - mysql
    environment:
      DOCKER: ${DOCKER}
      DB_HOST: ${DB_HOST}
      DB_HOST_DOCKER: ${DB_HOST_DOCKER}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - web
    environment:
      PORT: ${PORT}
      DOMAIN1: ${DOMAIN1}
      DOMAIN2: ${DOMAIN2}
    volumes:
      - $HOME/.caddy:/root/.caddy
